---
- name: "Check vars defined correctly"
  assert:
    that:
      - "calico_pool_name is defined"
      - "calico_pool_name | match('^[a-zA-Z0-9-_\\\\.]{2,63}$')"
      - "ipip_mode is defined"
      - "ipip_mode in ['Always', 'CrossSubnet', 'Never']"
    msg: "Check variable definitions seems something is wrong"
  run_once: yes

